### ISSUE TITLE
The missing of some constants in trainer

### ISSUE THREAD

**Issue by Ringbo** [natgen-team/NatGen#2]
Hi there, 

Thank you for the interesting work that attracted us. Although we encountered some minor issues while preprocessing the data, as follows:
1. there is no module named 'src.data_preprocessors.data'.
2. The definitions of the four constants OPTIMIZER_NAME, SCHEDULER_NAME, SCALER_NAME and TRAINER_STATE_NAME are missing in `semcode_trainer.py`.

Best

**Comment by saikat107** [comment]
Thanks for your interest. To solve these issues

1. Remove [this line](https://github.com/natgen-team/NatGen/blob/main/src/data_preprocessors/__init__.py#L2). We will soon update the code with patch. 
2. These constants are from [these lines](https://github.com/NielsRogge/transformers/blob/4bcf35471146c4e0eabfa8375a406fd177748d1a/src/transformers/trainer.py#L190-L194) from the transformers library. We tested it on transformers version 4.16.2. Make sure you are using the same.

**Comment by Ringbo** [comment]
Thanks for your reply.
